### ISSUE TITLE
TODOOVERDUE Interpreting #[[November 2020]] as criteria for "Overdue"

### ISSUE THREAD

**Issue by brandon-toner** [roamhacker/SmartBlocks#24]
## 🐞 Describe the behavior of the bug/issue you are encountering

Block containing #[[November 2020]] (and no other date references) is being pulled as reference when running TODOOVERDUE

## 💻 Environment

Platform:  macOS

Browser:  Vivaldi

## ✔️ Describe what you think the Expected Behavior should be

That block should be ignored.

HOWEVER, I'd love if #[[October 2020]] and earlier could be detected. 
**(This bug is nearly a feature lol)**
 

## 🔨 Describe any workarounds you've created/discovered

Ignore and move on

## 📷 Additional Info (Errors, Screenshots, GIFs, etc.)

![image](https://user-images.githubusercontent.com/67168828/100395798-b4775580-3018-11eb-9146-0e816c030534.png)

**Comment by brandon-toner** [comment]
![image](https://user-images.githubusercontent.com/67168828/100396587-f6ee6180-301b-11eb-8808-c488d1fe0c1a.png)

This one was returned as well... "#[[December 2020]]

**Comment by roamhacker** [comment]
I think this has been addressed as well. So closing out, but feel free to reopen if you find an issue.
