### ISSUE TITLE
Text insertion error behaviour with smartblock in the SideBar 

### ISSUE THREAD

**Issue by brandon-toner** [roamhacker/SmartBlocks#25]
## 🐞 Describe the behavior of the bug/issue you are encountering

1) Running a SmartBlock deletes the two characters before the block being entered. 
2) Couldn't select block using ENTER

## 💻 Environment

Platform:  MacOS

Browser:  Vivaldi

## 📜 Steps to reproduce the issue you are having

As shown in video

## 🔨 Describe any workarounds you've created/discovered

Add more space, wrestle with it a few times.

## 📷 Additional Info (Errors, Screenshots, GIFs, etc.)

https://www.loom.com/share/f7aa7c4341014626b73811a8cacda896

**Comment by brandon-toner** [comment]
Same behaviour in the linked references

**Comment by roamhacker** [comment]
Brandon, thank you for this report. Worked on this for a few hours and I think I have it fixed. No data loss -- always top priority.

Now, I can't promise its fixed, but please pay attention to see if it behaves.

**Comment by roamhacker** [comment]
I think this has been addressed as well. So closing out, but feel free to reopen if you find an issue.
