### ISSUE TITLE
Command prompting text sticking around after successful run when initiating with ENTER

### ISSUE THREAD

**Issue by brandon-toner** [roamhacker/SmartBlocks#27]
## 🐞 Describe the behavior of the bug/issue you are encountering

Extra text that's used to run the workflow is sticking around (";;plan"

## 💻 Environment

Platform:  MacOS

Browser:  Vivaldi

## ✔️ Describe what you think the Expected Behavior should be
 

Text should not persist after running. 

## 📜 Steps to reproduce the issue you are having

1. Initiate smartblock by typing ;;plan 
2. observe autopopulate
3.  press ENTER (*runs*)

## 🔨 Describe any workarounds you've created/discovered

Delete text after running

## 📷 Additional Info (Errors, Screenshots, GIFs, etc.)

https://www.loom.com/share/b1248da749e74940ba2e33b5685781c1

**Comment by roamhacker** [comment]
@brandon-toner can you let me know if this is still happening with the current testers build? If yes, can you send me the text of the workflow? I recreated it and it seems to be working, but perhaps there is some detail of the workflow I don't see in the video. Thank you for reporting this.

**Comment by brandon-toner** [comment]
I'll keep an eye — nothing noted yet.

**Comment by roamhacker** [comment]
I am going to close this out, as I think it is resolved.
