### ISSUE TITLE
Fetch Recent SmartBlocks from Github

### ISSUE THREAD

**Issue by achalaggarwal** [roamhacker/SmartBlocks#46]
## ✂️ Copy of your #42SmartBlock from Roam

Blocks #42SmartBlock
- <%NOBLOCKOUTPUT%><%SET:count,<%INPUT:Number of Blocks to Pull?%%5%>%>
- <%NOBLOCKOUTPUT%><%JAVASCRIPTASYNC:
```
var count = roam42.smartBlocks.activeWorkflow.vars["count"];
var url = "https://api.github.com/repos/roamhacker/smartblocks/issues?state=open&labels=SmartBlock&sort=updated&per_page="+count;
var responseText = $.ajax({url:url, type:"GET", async:false}).responseText;

var data = JSON.parse(responseText);
for(idx in data) {
  await roam42.smartBlocks.activeWorkflow.outputAdditionalBlock(
    data[idx].title + " [*](" + data[idx].url + ")"
  );
  await roam42.smartBlocks.outputArrayWrite();

  if(data[idx].body != undefined) {
    await roam42KeyboardLib.pressTab(20);
    await roam42.smartBlocks.outputArrayWrite();
		
    await roam42.smartBlocks.activeWorkflow.outputAdditionalBlock(data[idx].body);
    await roam42.smartBlocks.outputArrayWrite();

    await roam42KeyboardLib.pressShiftTab(20);
    await roam42.smartBlocks.outputArrayWrite()
  }
} 
return '';
```
%>

## 📋 Describe the SmartBlock

To fetch the latest SmartBlocks along with the description directly without having to come and see what's new as well as make it a little bit easier to install them

## ✅ Describe any prerequisites or dependencies that are required for this SmartBlock

Roam42 with Smartblocks

## 📷 Screenshot of your #42SmartBlock workflow/template from Roam

<img width="770" alt="image" src="https://user-images.githubusercontent.com/175970/100689998-a21c5500-3353-11eb-9a25-0ab9302164bd.png">

## 💡 Additional Info

![rcgO7E](https://user-images.githubusercontent.com/175970/100690188-fcb5b100-3353-11eb-823c-d3c947e3286f.gif)

**Comment by achalaggarwal** [comment]
@roamhacker I would love your input on this as I am trying to push child blocks but was not able to get that done without the workaround you see above. If there is a simpler way to do this, I want to extend this block to allow anyone to easily install other blocks as I see some folks having trouble installing.

**Comment by eurunuela** [comment]
This super super inspiring! I was thinking of building a SB like this to get my GitHub notifications into my daily notes as todos. Not sure it's possible though. Thank you for the inspiration!

**Comment by achalaggarwal** [comment]
> This super super inspiring! I was thinking of building a SB like this to get my GitHub notifications into my daily notes as todos. Not sure it's possible though. Thank you for the inspiration!

I actually built an integration to sync Airtable with my daily notes as TODOS as lot of us use that for tasks. But when I wanted to share it, it was too specific to my table structure. Therefore decided to do it with GitHub issues and realized that this could be something in itself.

**Comment by MehsEzeerf** [comment]
When I run this SB it asks me how many I want returned but then nothing else happens.  I don't think it copied directly into my DB well so I attempted to mess with it a bit to fix it but am now at a loss.

![image](https://user-images.githubusercontent.com/66741217/102703841-d5a71c80-4239-11eb-96cd-c97dd707aa96.png)

**Comment by eatondpe** [comment]
Hi, @achalaggarwal. We recently had a minor incident with this SmartBlock and would like to discuss this with you. We had a user who used it, and after it copied a large number of SmartBlocks into his graph his other javascripts started failing. Most likely a conflict somewhere.

This is an amazing piece of work. But as the number of SmartBlocks grows, and grows from an ever expanding group of Roamans, there is concern it may have reached its limit. @roamhacker is preparing to open up SmartBlocks to the rest of the Roam community which will further increase the number of submission to the SmartBlocks repository, while also expanding the number of people who are unaware of how many SmartBlocks this would add to their graphs or whether or not all of those SmartBlocks are safe.

For these reasons, we are proposing that you retire this SmartBlock. What are your thoughts?

**Comment by achalaggarwal** [comment]
> Hi, @achalaggarwal. We recently had a minor incident with this SmartBlock and would like to discuss this with you. We had a user who used it, and after it copied a large number of SmartBlocks into his graph his other javascripts started failing. Most likely a conflict somewhere.
> 
> 
> 
> This is an amazing piece of work. But as the number of SmartBlocks grows, and grows from an ever expanding group of Roamans, there is concern it may have reached its limit. @roamhacker is preparing to open up SmartBlocks to the rest of the Roam community which will further increase the number of submission to the SmartBlocks repository, while also expanding the number of people who are unaware of how many SmartBlocks this would add to their graphs or whether or not all of those SmartBlocks are safe.
> 
> 
> 
> For these reasons, we are proposing that you retire this SmartBlock. What are your thoughts?

I am just looking at this now. Somehow this got lost in the notifications. Removing this so it does not cause any issues.
